# Generated by Django 4.1.5 on 2023-01-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Event Name')),
                ('event_date', models.DateTimeField(verbose_name='Date')),
                ('venue', models.CharField(max_length=50, verbose_name='Venue')),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
